# translation of firstboot.master.po to Persian(fa)
# translation of firstboot to Persian
# Copyright (C) 2003, 2004 Abbas Izad.
# Copyright (C) 2005, 2006 Sharif FarsiWeb, Inc.
# Copyright (C) 2008 Amir Farsi.
# Abbas Izad <abbasizad@hotmail.com>, 2003, 2004.
# Hamed Malek <hamed@bamdad.org>, 2005
# Meelad Zakaria <meelad@farsiweb.info>, 2005, 2006.
# Roozbeh Pournader <roozbeh@farsiweb.info>, 2006.
# Elnaz Sarbar <elnaz@farsiweb.info>, 2006.
# Amir Farsi <afarsi@ymail.com>, 2008
msgid ""
msgstr ""
"Project-Id-Version: firstboot.master\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-03-12 16:50-0400\n"
"PO-Revision-Date: 2008-07-19 06:41+0330\n"
"Last-Translator: Amir Farsi\n"
"Language-Team: Persian(fa) <fedora-trans-fa@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"

#: ../progs/firstboot:140
msgid "You must be root to run firstboot."
msgstr "برای اجرای firstboot شما باید کاربر root باشید."

#: ../progs/firstboot:163 ../progs/firstboot:164
msgid "Could not start any firstboot frontend."
msgstr ""

#: ../progs/firstboot:180 ../progs/firstboot:181
msgid "No firstboot modules were found."
msgstr ""

#: ../progs/firstboot:190 ../progs/firstboot:191
msgid "Could not create any firstboot interface."
msgstr ""

#: ../firstboot/exceptionWindow.py:50
#, python-format
msgid "An error has occurred in the %s module."
msgstr "‌خطایی در پیمانهٔ %s رخ داده است."

#: ../firstboot/exceptionWindow.py:51
#, python-format
msgid ""
"Since there is a problem with the %s module,\n"
"firstboot will not load this module and will\n"
"attempt to run the remaining modules."
msgstr ""

#: ../firstboot/exceptionWindow.py:55
msgid "An error has occurred in firstboot."
msgstr "یک خطا در firstboot رخ داده است"

#: ../firstboot/exceptionWindow.py:56
msgid "Since there is a problem, firstboot will exit."
msgstr ""

#: ../firstboot/exceptionWindow.py:66
#, python-format
msgid ""
"A copy of the debug output has been saved to %s\n"
"Be sure to attach that file to the bug report.\n"
msgstr ""

#: ../firstboot/exceptionWindow.py:71
msgid ""
"Please file a bug against 'firstboot' in the Red Hat\n"
"bug tracking system at http://www.redhat.com/bugzilla.\n"
msgstr ""

#: ../firstboot/interface.py:75
msgid "Attempted to go back, but history is empty."
msgstr ""

#. If we were previously on the last page, we need to set the Next
#. button's label back to normal.
#: ../firstboot/interface.py:83 ../firstboot/interface.py:162
msgid "_Finish"
msgstr "ـپایان"

#: ../firstboot/interface.py:183
msgid "The system must now reboot for some of your selections to take effect."
msgstr ""

#: ../firstboot/interface.py:243
msgid "_Back"
msgstr "_عقب"

#: ../firstboot/interface.py:250
msgid "_Forward"
msgstr "ـجلو"

#: ../firstboot/interface.py:277
#, python-format
msgid "Module %s did not set up its UI, removing."
msgstr ""

#: ../firstboot/interface.py:353 ../firstboot/interface.py:354
msgid "moveToPage must be given a module title or page number."
msgstr ""

#: ../firstboot/interface.py:438
msgid "Unable to create the screenshot dir; skipping."
msgstr "قادر به ایجاد پوشه screenshot نمیباشد، در حال رد کردن."

#: ../firstboot/interface.py:478 ../firstboot/interface.py:479
#, python-format
msgid "No module exists with the title %s."
msgstr "هیچ ماژولی با عنوان %s وجود ندارد."

#: ../firstboot/loader.py:90
#, python-format
msgid "Skipping old module %s that has not been updated."
msgstr ""

#: ../firstboot/loader.py:102
#, python-format
msgid "Module %s does not contain a class named moduleClass; skipping."
msgstr ""

#: ../firstboot/loader.py:113
#, python-format
msgid "Module %s does not contain the required attribute %s; skipping."
msgstr ""

#: ../firstboot/module.py:187
#, python-format
msgid "Unable to load pixmap %s for module %s."
msgstr ""

#: ../firstboot/moduleset.py:93
#, python-format
msgid "Module %s did not set up its UI; removing."
msgstr ""

#: ../modules/additional_cds.py:43 ../modules/additional_cds.py:44
msgid "Additional CDs"
msgstr "سی دی های اضافی"

#: ../modules/additional_cds.py:55
msgid ""
"Please insert the disc labeled \"Red Hat Enterprise Linux Extras\" to allow "
"for installation of third-party plug-ins and applications.  You may also "
"insert the Documentation disc, or other Red Hat-provided discs to install "
"additional software at this time."
msgstr ""
"لطفاً دیسکی را که برچسب «اضافات لینوکس انترپرایز رِدهَت» دارد وارد کنید تا نصب "
"متصل‌شونده‌ها و برنامه‌های طرف سوم ممکن شود. همچنین می‌توانید دیسک مستندات یا "
"دیسک‌های دیگر ارائه شده توسط رِدهَت را وارد کنید تا نرم‌افزارهای اضافی نصب شوند."

#: ../modules/additional_cds.py:61
msgid "Please insert any additional software install cds at this time."
msgstr "هم اکنون لطفا سی دی هرگونه نرم افزار اضافی را قرار دهید"

#: ../modules/additional_cds.py:65
msgid ""
"\n"
"\n"
"To enable runtime support of 32-bit applications on the Intel Itanium2 "
"architecture you must install the Intel Execution Layer package from the "
"Extras disc now."
msgstr ""

#: ../modules/additional_cds.py:73
msgid "Install..."
msgstr "نصب..."

#: ../modules/additional_cds.py:110
msgid ""
"A CD-ROM has not been detected.  Please insert a CD-ROM in the drive and "
"click \"OK\" to continue."
msgstr ""
"سی‌دی تشخیص داده نشده است. لطفاً یک سی‌دی را در دستگاه گذاشته و برای ادامه روی "
"«تأیید» کلیک کنید."

#: ../modules/additional_cds.py:146
msgid ""
"The autorun program cannot be found on the CD. Click \"OK\" to continue."
msgstr ""

#: ../modules/create_user.py:41 ../modules/create_user.py:42
msgid "Create User"
msgstr "ایجاد کاربر"

#: ../modules/create_user.py:83
#, fuzzy
msgid "You must create a user account for this system."
msgstr "لطفا تاریخ و ساعت را برای سیستم تنظیم کنید."

#: ../modules/create_user.py:94
msgid "You must enter and confirm a password for this user."
msgstr ""

#: ../modules/create_user.py:101
msgid "The passwords do not match.  Please enter the password again."
msgstr "رمزهای عبور همخوانی ندارند. لطفا رمز عبور را دوباره وارد کنید."

#: ../modules/create_user.py:113
#, python-format
msgid ""
"The username '%s' is a reserved system account.  Please specify another "
"username."
msgstr ""

#: ../modules/create_user.py:132
#, fuzzy, python-format
msgid ""
"A home directory for user %s already exists. Would you like to continue, "
"making the new user the owner of this directory and all its contents?  Doing "
"so may take a while to reset permissions and any SELinux labels.  Would you "
"like to reuse this home directory?  If not, please choose a different "
"username."
msgstr ""
"یک پوشه آغازه(home) برای کاربر %s یافت شده است. آیا شما دوست دارید مجددا از "
"پوشه آغازه(home) استفاده کنید؟ اگر نه، لطفا یک نام کاربری متفاوت را انتخاب "
"کنید."

#: ../modules/create_user.py:175
#, python-format
msgid ""
"Fixing attributes on the home directory for %s.  This may take a few minutes."
msgstr ""

#: ../modules/create_user.py:195
#, python-format
msgid ""
"Problems were encountered fixing the attributes on some files in the home "
"directory for %s.  Please refer to %s for which files caused the errors."
msgstr ""

#: ../modules/create_user.py:213
#, fuzzy
msgid ""
"You must create a 'username' for regular (non-administrative) use of your "
"system.  To create a system 'username', please provide the information "
"requested below."
msgstr ""
"این توصیه شده است که شما یک نام کاربری برای استفاده ویژه(غیر مدیریتی) سیستم "
"خودتان ایجاد کنید. برای ایجاد نام کاربری، لطفا اطلاعاتی که در زیر درخواست "
"شده است را ارایه دهید."

#: ../modules/create_user.py:231
msgid "_Username:"
msgstr "نام کـارـبری:"

#: ../modules/create_user.py:238
msgid "Full Nam_e:"
msgstr "نام ـکـامل:"

#: ../modules/create_user.py:245
msgid "_Password:"
msgstr "ـرمز عبور:"

#: ../modules/create_user.py:252
msgid "Confir_m Password:"
msgstr "تایید رـمز عبور:"

#: ../modules/create_user.py:261
msgid ""
"If you need to use network authentication, such as Kerberos or NIS, please "
"click the Use Network Login button."
msgstr ""

#: ../modules/create_user.py:270
msgid "Use Network _Login..."
msgstr ""

#: ../modules/create_user.py:308
msgid "Please wait"
msgstr ""

#: ../modules/date.py:40 ../modules/date.py:41
msgid "Date and Time"
msgstr "تاریخ و ساعت"

#: ../modules/date.py:62
msgid "Please set the date and time for the system."
msgstr "لطفا تاریخ و ساعت را برای سیستم تنظیم کنید."

#: ../modules/eula.py:35 ../modules/eula.py:36
msgid "License Information"
msgstr "اطلاعات لیسانس"

#: ../modules/eula.py:53
msgid ""
"Thank you for installing Fedora.  Fedora is a compilation of software "
"packages, each under its own license.  The compilation is made available "
"under the GNU General Public License version 2.  There are no restrictions "
"on using, copying, or modifying this code.  However, there are restrictions "
"and obligations that apply to the redistribution of the code, either in its "
"original or a modified form.  Among other things, those restrictions/"
"obligations pertain to the licensing of the redistribution, trademark "
"rights, and export control.\n"
"\n"
"If you would like to understand what those restrictions are, please visit "
"http://fedoraproject.org/wiki/Legal/Licenses/LicenseAgreement."
msgstr ""

#: ../modules/eula.py:64
msgid "Understood, please proceed."
msgstr ""

#: ../modules/welcome.py:35 ../modules/welcome.py:36
msgid "Welcome"
msgstr "خوش آمدید"

#: ../modules/welcome.py:45
msgid ""
"There are a few more steps to take before your system is ready to use.  The "
"Setup Agent will now guide you through some basic configuration.  Please "
"click the \"Forward\" button in the lower right corner to continue"
msgstr ""

#~ msgid ""
#~ "It is highly recommended that a personal user account be created.  If you "
#~ "continue without an account, you can only log in with the root account, "
#~ "which is reserved for administrative use only."
#~ msgstr ""
#~ "این بسیار توصیه شده است که یک حساب کاربری شخصی ایجاد شود. اگر شما بدون یک "
#~ "حساب ادامه دهید، شما فقط میتوانید با حساب root که برای استفاده مدیریتی "
#~ "ذخیره شده است وارد شوید."

#~ msgid "_Continue"
#~ msgstr "ـادامه"

#~ msgid "Create _account"
#~ msgstr "ایجاد ـحساب"
