# Copyright (C) 2004 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Automatically generated, 2004.
#
msgid ""
msgstr ""
"Project-Id-Version: firstboot\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-03-12 16:50-0400\n"
"PO-Revision-Date: 2006-03-22 21:23+0500\n"
"Last-Translator: Usman Siraj Sheikh <usman.siraj@gmail.com>\n"
"Language-Team: SCS GIFT UNIVERSITY (http://cs.gift.edu.pk) <urdu.scs."
"gift@gmail.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-Language: Urdu\n"
"X-Poedit-Country: Pakistan\n"

#: ../progs/firstboot:140
msgid "You must be root to run firstboot."
msgstr ""

#: ../progs/firstboot:163 ../progs/firstboot:164
msgid "Could not start any firstboot frontend."
msgstr ""

#: ../progs/firstboot:180 ../progs/firstboot:181
msgid "No firstboot modules were found."
msgstr ""

#: ../progs/firstboot:190 ../progs/firstboot:191
msgid "Could not create any firstboot interface."
msgstr ""

#: ../firstboot/exceptionWindow.py:50
#, python-format
msgid "An error has occurred in the %s module."
msgstr " میں ایک مسلہ آ چکا ہے %s حصہ"

#: ../firstboot/exceptionWindow.py:51
#, fuzzy, python-format
msgid ""
"Since there is a problem with the %s module,\n"
"firstboot will not load this module and will\n"
"attempt to run the remaining modules."
msgstr ""
"  میں ابھی تک مسُلہ ہے,\n"
" ریڑہیٹ سیٹپ ایجنٹ اس حصہ کو نہیں لادے گا اور بقایا حصوں کو چلانے کی کوشش "
"کرے گا  \n"
" ۔%sحصہ "

#: ../firstboot/exceptionWindow.py:55
#, fuzzy
msgid "An error has occurred in firstboot."
msgstr " میں ایک مسلہ آ چکا ہے %s حصہ"

#: ../firstboot/exceptionWindow.py:56
msgid "Since there is a problem, firstboot will exit."
msgstr ""

#: ../firstboot/exceptionWindow.py:66
#, fuzzy, python-format
msgid ""
"A copy of the debug output has been saved to %s\n"
"Be sure to attach that file to the bug report.\n"
msgstr ""
"مہربانی فرما کر ریڈ ہیٹ کے نقص کو جانچنے والے سسٹم میں \n"
"پر 'firstboot'کے خلاف نقص درج کریں http://www.redhat.com/bugzilla. \n"
"آوٹپٹ کی نقل میں محفوظ کر دی جاےُ گی  %s \n"
"Be sure to attach that file to the bug report. \n"

#: ../firstboot/exceptionWindow.py:71
#, fuzzy
msgid ""
"Please file a bug against 'firstboot' in the Red Hat\n"
"bug tracking system at http://www.redhat.com/bugzilla.\n"
msgstr ""
"مہربانی فرما کر ریڈ ہیٹ کے نقص کو جانچنے والے سسٹم میں \n"
"پر 'firstboot'کے خلاف نقص درج کریں http://www.redhat.com/bugzilla. \n"
"آوٹپٹ کی نقل میں محفوظ کر دی جاےُ گی  %s \n"
"Be sure to attach that file to the bug report. \n"

#: ../firstboot/interface.py:75
msgid "Attempted to go back, but history is empty."
msgstr ""

#. If we were previously on the last page, we need to set the Next
#. button's label back to normal.
#: ../firstboot/interface.py:83 ../firstboot/interface.py:162
msgid "_Finish"
msgstr "اختتام"

#: ../firstboot/interface.py:183
msgid "The system must now reboot for some of your selections to take effect."
msgstr "آپ کےانتخابات کو بااثر کرنے کے لیے سسٹم لازمن دوبارہ بوٹ کرتا ہے"

#: ../firstboot/interface.py:243
msgid "_Back"
msgstr "پيچھے"

#: ../firstboot/interface.py:250
msgid "_Forward"
msgstr "آگے_"

#: ../firstboot/interface.py:277
#, python-format
msgid "Module %s did not set up its UI, removing."
msgstr ""

#: ../firstboot/interface.py:353 ../firstboot/interface.py:354
msgid "moveToPage must be given a module title or page number."
msgstr ""

#: ../firstboot/interface.py:438
msgid "Unable to create the screenshot dir; skipping."
msgstr ""

#: ../firstboot/interface.py:478 ../firstboot/interface.py:479
#, python-format
msgid "No module exists with the title %s."
msgstr ""

#: ../firstboot/loader.py:90
#, python-format
msgid "Skipping old module %s that has not been updated."
msgstr ""

#: ../firstboot/loader.py:102
#, python-format
msgid "Module %s does not contain a class named moduleClass; skipping."
msgstr ""

#: ../firstboot/loader.py:113
#, python-format
msgid "Module %s does not contain the required attribute %s; skipping."
msgstr ""

#: ../firstboot/module.py:187
#, python-format
msgid "Unable to load pixmap %s for module %s."
msgstr ""

#: ../firstboot/moduleset.py:93
#, python-format
msgid "Module %s did not set up its UI; removing."
msgstr ""

#: ../modules/additional_cds.py:43 ../modules/additional_cds.py:44
msgid "Additional CDs"
msgstr "مزید سیڈ یز"

#: ../modules/additional_cds.py:55
msgid ""
"Please insert the disc labeled \"Red Hat Enterprise Linux Extras\" to allow "
"for installation of third-party plug-ins and applications.  You may also "
"insert the Documentation disc, or other Red Hat-provided discs to install "
"additional software at this time."
msgstr ""
" لکھا ہے ۔ اور آپ دستا ویزات والی سی ڈی بھی ڈالیں یا مزید سافٹ ویرز کے لیے "
"وہ سی ڈی ڈالیں جو ریڈ ہیٹ نے مہیا کی ہے۔\"Red Hat Enterprise Linux Extras\" "
"تیسری جماعت کے پلگ ان اور سافٹ ویر کی نصب کاری کو اجازت دینے کے لیے "
"براےمہربانی وہ ڈسک ڈالیں جس پر  "

#: ../modules/additional_cds.py:61
msgid "Please insert any additional software install cds at this time."
msgstr "براے مہربانی اس وقت مزید سافٹ ویر کی نصب کاری کے لیے سیڈ یز ڈالیں۔  "

#: ../modules/additional_cds.py:65
msgid ""
"\n"
"\n"
"To enable runtime support of 32-bit applications on the Intel Itanium2 "
"architecture you must install the Intel Execution Layer package from the "
"Extras disc now."
msgstr ""
"\n"
"\n"
"انٹیل ایٹینین ۲ آرچیٹیکچر پر  ایپلیکیشنزbit-32کے چلنے کا ساتھ چالو کرنے کے "
"لیُے اپ کو  ابھی اضافی ڈیکس میں سے انٹیل ایکسیکیوشن لیُر پیکج نصب کرنا پڑے گا۔ "

#: ../modules/additional_cds.py:73
msgid "Install..."
msgstr "نصب کریں "

#: ../modules/additional_cds.py:110
msgid ""
"A CD-ROM has not been detected.  Please insert a CD-ROM in the drive and "
"click \"OK\" to continue."
msgstr ""
" کا سراغ نہیں لگا۔ براے مہربا نی ڈرایوّ میں سی ڈی ڈالیں اور اوکے کو دباو جاری "
"رکھنے کے کیے۔ ۔ ۔ CD-ROM"

#: ../modules/additional_cds.py:146
msgid ""
"The autorun program cannot be found on the CD. Click \"OK\" to continue."
msgstr "سی ڈی پر خودکار پروگرام نہیں ملا۔ جاری رکھنے کے لیے \"اوکے \"د بایں"

#: ../modules/create_user.py:41 ../modules/create_user.py:42
msgid "Create User"
msgstr ""

#: ../modules/create_user.py:83
msgid "You must create a user account for this system."
msgstr ""

#: ../modules/create_user.py:94
msgid "You must enter and confirm a password for this user."
msgstr ""

#: ../modules/create_user.py:101
msgid "The passwords do not match.  Please enter the password again."
msgstr ""

#: ../modules/create_user.py:113
#, python-format
msgid ""
"The username '%s' is a reserved system account.  Please specify another "
"username."
msgstr ""

#: ../modules/create_user.py:132
#, python-format
msgid ""
"A home directory for user %s already exists. Would you like to continue, "
"making the new user the owner of this directory and all its contents?  Doing "
"so may take a while to reset permissions and any SELinux labels.  Would you "
"like to reuse this home directory?  If not, please choose a different "
"username."
msgstr ""

#: ../modules/create_user.py:175
#, python-format
msgid ""
"Fixing attributes on the home directory for %s.  This may take a few minutes."
msgstr ""

#: ../modules/create_user.py:195
#, python-format
msgid ""
"Problems were encountered fixing the attributes on some files in the home "
"directory for %s.  Please refer to %s for which files caused the errors."
msgstr ""

#: ../modules/create_user.py:213
msgid ""
"You must create a 'username' for regular (non-administrative) use of your "
"system.  To create a system 'username', please provide the information "
"requested below."
msgstr ""

#: ../modules/create_user.py:231
msgid "_Username:"
msgstr ""

#: ../modules/create_user.py:238
msgid "Full Nam_e:"
msgstr ""

#: ../modules/create_user.py:245
msgid "_Password:"
msgstr ""

#: ../modules/create_user.py:252
msgid "Confir_m Password:"
msgstr ""

#: ../modules/create_user.py:261
msgid ""
"If you need to use network authentication, such as Kerberos or NIS, please "
"click the Use Network Login button."
msgstr ""

#: ../modules/create_user.py:270
msgid "Use Network _Login..."
msgstr ""

#: ../modules/create_user.py:308
msgid "Please wait"
msgstr ""

#: ../modules/date.py:40 ../modules/date.py:41
msgid "Date and Time"
msgstr ""

#: ../modules/date.py:62
msgid "Please set the date and time for the system."
msgstr ""

#: ../modules/eula.py:35 ../modules/eula.py:36
#, fuzzy
msgid "License Information"
msgstr "وقت چکر کی رچاوٹ"

#: ../modules/eula.py:53
msgid ""
"Thank you for installing Fedora.  Fedora is a compilation of software "
"packages, each under its own license.  The compilation is made available "
"under the GNU General Public License version 2.  There are no restrictions "
"on using, copying, or modifying this code.  However, there are restrictions "
"and obligations that apply to the redistribution of the code, either in its "
"original or a modified form.  Among other things, those restrictions/"
"obligations pertain to the licensing of the redistribution, trademark "
"rights, and export control.\n"
"\n"
"If you would like to understand what those restrictions are, please visit "
"http://fedoraproject.org/wiki/Legal/Licenses/LicenseAgreement."
msgstr ""

#: ../modules/eula.py:64
msgid "Understood, please proceed."
msgstr ""

#: ../modules/welcome.py:35 ../modules/welcome.py:36
msgid "Welcome"
msgstr "خوش آمد ید"

#: ../modules/welcome.py:45
#, fuzzy
msgid ""
"There are a few more steps to take before your system is ready to use.  The "
"Setup Agent will now guide you through some basic configuration.  Please "
"click the \"Forward\" button in the lower right corner to continue"
msgstr ""
"  آپ کا سسٹم استمال کے لیے تیار ہو اس سے پہلے  یہاں کچھ مزید اقدام بروکار "
"لانے ہیں۔ سیٹپ ایجنٹ اب کچھ بنیادی رچاوٹ کے زریعے آپ کی رہنمای کرے گا۔ براۓ "
"مہربانی جاری رکھنے کے لیے آگے کا بٹن د بائں جو کہ دائں طرف نیچے والے کونے "
"میں ہے۔ "
